POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "123456"
}

###
GET http://localhost:4000/healthcheck HTTP/1.1
Authorization: "Bearer "

### All Events
GET http://localhost:4000/events

### event by id
GET http://localhost:4000/events/5e25282b-cde5-45ff-9436-c4320d7c2f6f

### validate event alias
GET http://localhost:4000/events/validate/evento-fullstack

### acessar evento
POST http://localhost:4000/events/acessar
Content-Type: application/json

{
    "id": "65965e1c-8055-4795-b4a3-da93bbe97e31",
    "senha": "familia2024"
}

### event by Id
GET http://localhost:4000/events/1

###
POST http://localhost:4000/events/reuniao-familia-oliveira/convidado
Content-Type: application/json

{
    "id": "f7f5279c-e271-49e8-b1b2-b2d413f3044e",
    "nome": "Leonardo Leitão",
    "email": "leonardo@formacao.dev",
    "confirmado": true,
    "possuiAcompanhantes": true,
    "qtdeAcompanhantes": 10
}

###
# POST http://localhost:4000/events
# Content-Type: application/json

# {
#     "id": 1243475675,
#     "alias": "semana-formacao-dev",
#     "nome": "Evento Semana Formação.DEV",
#     "data": "2025-12-31T23:00",
#     "local": "São Paulo",
#     "descricao": "Evento de tecnologia",
#     "senha": "frameworks2025",
#     "imagem": "https://www.formacao.dev/assets/img/formacao-dev.png",
#     "imagemBackground": "https://www.formacao.dev/assets/img/formacao-dev-background.png",
#     "publicoEsperado": 1000,
#     "convidados": [
#         {
#             "nome": "Leonardo Leitão",
#             "email": "leonardo@formacao.dev",
#             "confirmado": true,
#             "possuiAcompanhantes": true,
#             "qtdeAcompanhantes": 10
#         }
#     ]
# }

### create event
POST http://localhost:4000/events
Content-Type: application/json

{
  "name": "evento 2",
  "description": "evento 2",
  "startDate": "2025-01-17T12:04:00.000Z",
  "local": "evento2",
  "address": "evento2",
  "password": "evento21234",
  "expectedAudience": 100,
  "image": "https://media.istockphoto.com/id/974238866/pt/foto/audience-listens-to-the-lecturer-at-the-conference.jpg?s=612x612&w=0&k=20&c=ZOCjHsr2nyWVvAgjA36Kg1FaIQpvQ3oThxEf_W7JdCc=",
  "keyPix": "645377675436345",
  "monetize": true,
  "imageBackground": "https://media.istockphoto.com/id/974238866/pt/foto/audience-listens-to-the-lecturer-at-the-conference.jpg?s=612x612&w=0&k=20&c=ZOCjHsr2nyWVvAgjA36Kg1FaIQpvQ3oThxEf_W7JdCc=",
  "alias": "teste-evento-2",
  "userId": 1
}

### Create User
POST http://localhost:4000/users
Content-Type: application/json

{
  "name": "Dayane",
  "email": "dayane@localhost.com",
  "password": "davi123456"
}

### Find User by Id
GET http://localhost:4000/users/1

### Find Event By Alias
GET http://localhost:4000/events/alias/asdasdasd


### Create Guest into event
POST http://localhost:4000/guests/asdasdasd/guest
Content-Type: application/json

{
  "name": "Dana Smith",
  "email": "dana.smith@example.com"
}
